// src/components/nakshatraPada/NakshatraPada.tsx
import type { TargetedSubmitEvent } from 'preact';
import { NAKSHATRA_FULL_NAMES } from '../../data/constants';
import { Select } from '../ui';
import styles from './NakshatraPada.module.scss';
import { useState } from 'preact/hooks';
import { NakshatraPadaData } from '../../data/NakshatraPada.data';
import type { NakshatraData, NakshatraPadas, PadaInfo } from '../../models';

export const NakshatraPada = () => {
  const [selectedPadaInfo, setSelectedPadainfo] = useState<PadaInfo>();

  const handleSubmit = (e: TargetedSubmitEvent<HTMLFormElement>) => {
    e.preventDefault();
    const formData = new FormData(e.target as HTMLFormElement);
    const selectedNakshatra = formData.get('nakshatra') as keyof NakshatraData;
    const selectedPada = formData.get('pada') as keyof NakshatraPadas;
    const data = NakshatraPadaData[selectedNakshatra][selectedPada];
    setSelectedPadainfo(data);
  };

  return (
    <div>
      <form className={styles.nakshatraPadaForm} onSubmit={handleSubmit}>
        <Select
          fieldName="nakshatra"
          label="Select Nakshatra"
          options={[
            { label: 'Select', value: '' },
            ...Object.entries(NAKSHATRA_FULL_NAMES).map(([key, value]) => {
              return { label: value, value: key };
            })
          ]}
        />
        <Select
          fieldName="pada"
          label="Select Pada"
          options={[
            {
              label: 'Select',
              value: ''
            },
            {
              label: 'Pada 1',
              value: '1'
            },
            {
              label: 'Pada 2',
              value: '2'
            },
            {
              label: 'Pada 3',
              value: '3'
            },
            {
              label: 'Pada 4',
              value: '4'
            }
          ]}
        />
        <button type="submit">Submit</button>
      </form>
      <div>
        <pre>
          <code>{JSON.stringify(selectedPadaInfo, null, 2)}</code>
        </pre>
      </div>
    </div>
  );
};

// src/features/nakshatraPada/nakshatra-pada.component.ts
import { CommonModule } from '@angular/common';
import { Component, signal } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
import { NAKSHATRA_FULL_NAMES } from '../../data/constants';
import { NakshatraPadaData } from '../../data/NakshatraPada.data';
import { PadaInfo } from '../../shared/models';
import { SelectComponent } from '../../shared/ui';

@Component({
  selector: 'app-nakshatra-pada',
  standalone: true,
  imports: [CommonModule, FormsModule, SelectComponent],
  templateUrl: './nakshatra-pada.component.html',
  styleUrls: ['./nakshatra-pada.component.scss']
})
export class NakshatraPadaComponent {
  // Signal to hold the result
  selectedNakshatra = '';
  selectedPada = '';
  selectedPadaInfo = signal<PadaInfo | null>(null);

  // Transform constants for the Select component
  nakshatraOptions = [
    { label: 'Select', value: '' },
    ...Object.entries(NAKSHATRA_FULL_NAMES).map(([key, value]) => ({
      label: value,
      value: key
    }))
  ];

  padaOptions = [
    { label: 'Select', value: '' },
    { label: 'Pada 1', value: '1' },
    { label: 'Pada 2', value: '2' },
    { label: 'Pada 3', value: '3' },
    { label: 'Pada 4', value: '4' }
  ];

  onSubmit(form: NgForm) {
    if (this.selectedNakshatra && this.selectedPada) {
      const data = (NakshatraPadaData as any)[this.selectedNakshatra][this.selectedPada];
      this.selectedPadaInfo.set(data);
    }
  }
}

<div class="nakshatra-pada-container">
  <form
    #padaForm="ngForm"
    (ngSubmit)="onSubmit(padaForm)"
    class="nakshatra-pada-form"
  >
    <app-select
      label="Select Nakshatra"
      [options]="nakshatraOptions"
      [(value)]="selectedNakshatra"
      fieldName="nakshatra"
    ></app-select>

    <app-select
      label="Select Pada"
      [options]="padaOptions"
      [(value)]="selectedPada"
      fieldName="pada"
    ></app-select>

    <button type="submit">Submit</button>
  </form>

  @if (selectedPadaInfo()) {
  <div>
    <pre>
      <code>{{ selectedPadaInfo() | json }}</code>
    </pre>
  </div>
  }
</div>
