// src/features/astroParseTable/astro-parse-table.component.ts
import {
  Component,
  ElementRef,
  ViewChild,
  signal,
  computed,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AstroParseTableService } from './astro-parse-table.service';
import { AstroRowData } from './astro-parse-table.model';
import { KarmicDoshas } from '../../data/karmicDoshas';
import { NakshatraPadaData } from '../../data/nakshatraPada.data';

@Component({
  selector: 'app-astro-parse-table',
  standalone: true,
  imports: [CommonModule, FormsModule],
  providers: [AstroParseTableService],
  templateUrl: './astro-parse-table.component.html',
  styleUrls: ['./astro-parse-table.component.scss'],
})
export class AstroParseTableComponent {
  private astroService = inject(AstroParseTableService);

  // State Signals
  input = signal('');
  rows = signal<AstroRowData[]>([]);
  planetMatrix = signal<Record<string, number>>({});

  // Hover State
  hoveredRow = signal<number | null>(null);
  hoveredCol = signal<number | null>(null);

  // Modal State
  selectedDosha = signal<any>(null);
  karmicResultsHtml = signal('');

  @ViewChild('doshaDialog') doshaDialog!: ElementRef<HTMLDialogElement>;
  @ViewChild('resultsDialog') resultsDialog!: ElementRef<HTMLDialogElement>;

  planets = [
    { name: 'As' },
    { name: 'Sun' },
    { name: 'Moon' },
    { name: 'Mars' },
    { name: 'Mercury' },
    { name: 'Jupiter' },
    { name: 'Venus' },
    { name: 'Saturn' },
    { name: 'Rahu' },
    { name: 'Ketu' },
    { name: 'Uranus' },
    { name: 'Neptune' },
    { name: 'Pluto' },
    { name: 'Maandi' },
    { name: 'Bhrigu Bindu' },
  ];

  protected readonly NakshatraPadaData = NakshatraPadaData as any;

  handleSubmit() {
    const result = this.astroService.processInput(this.input());
    this.rows.set(result.rows);
    this.planetMatrix.set(result.matrix);
  }

  getDistance(a: string, b: string) {
    return this.astroService.getRasiDistances(a, b);
  }

  // Hover logic
  setHover(row: number | null, col: number | null) {
    this.hoveredRow.set(row);
    this.hoveredCol.set(col);
  }

  getCellBg(row: number, col: number): string {
    const isRow = this.hoveredRow() === row;
    const isCol = this.hoveredCol() === col;
    if (isRow && isCol) return '#ffeb3b';
    if (isRow || isCol) return '#fff3cd';
    return 'transparent';
  }

  // Dialog actions
  openDosha(code: string, rasi: string) {
    this.selectedDosha.set({ ...KarmicDoshas[code], rasi });
    this.doshaDialog.nativeElement.showModal();
  }

  openResults(html: string) {
    this.karmicResultsHtml.set(html);
    this.resultsDialog.nativeElement.showModal();
  }
}

<textarea
  rows="15"
  [(ngModel)]="input"
  placeholder="Paste astrology data here..."
  class="formControl"
></textarea>

<div class="text-center actions">
  <button (click)="handleSubmit()">Generate Table</button>
</div>

@if (rows().length > 0) {
<details open>
  <summary><strong>Planet Details</strong></summary>
  <div class="table-responsive">
    <table class="planetDetails">
      <thead>
        <tr>
          <th>Body</th>
          <th>Longitude</th>
          <th>Nakshatra</th>
          <th>Pada</th>
          <th>Rasi (D1)</th>
          <th>Navamsa (D9)</th>
          <th>Rasi Combination</th>
          <th>Characteristics</th>
          <th>Career Path</th>
          <th>Karmic Dosha</th>
          <th>Karmic Planet</th>
        </tr>
      </thead>
      <tbody>
        @for (row of rows(); track $index) {
        <tr>
          <td>{{ row.body }}</td>
          <td>{{ row.longitude }}</td>
          <td>{{ row.nakshatra }}</td>
          <td>{{ row.pada }}</td>
          <td>{{ row.rasi }}</td>
          <td>{{ row.navamsa }}</td>
          <td>{{ getDistance(row.rasiCode, row.navamsaCode) }}</td>
          <td>
            {{
              NakshatraPadaData[row.nakshatraCode][row.pada]['Characteristics']
            }}
          </td>
          <td>
            {{ NakshatraPadaData[row.nakshatraCode][row.pada]['Career Path'] }}
          </td>
          <td>
            @if (row.hasKarmicDosha) {
            <span>Yes</span>
            <button
              data-size="sm"
              (click)="openDosha(row.nakshatraCode, row.rasi)"
            >
              View
            </button>
            } @else { No }
          </td>
          <td>
            {{ row.karmicPlanet }}
            <button
              data-size="sm"
              (click)="openResults(row.karmicPlanetResults)"
            >
              View
            </button>
          </td>
        </tr>
        }
      </tbody>
    </table>
  </div>
</details>

<details>
  <summary><strong>Navamsa Matrix</strong></summary>
  <div class="table-responsive">
    <table class="matrixTable">
      <thead>
        <tr>
          <th></th>
          @for (p of planets; track p.name) {
          <th
            [style.background-color]="hoveredCol() === $index ? '#fff3cd' : ''"
          >
            {{ p.name }}
          </th>
          }
        </tr>
      </thead>
      <tbody>
        @for (rowP of planets; track rowP.name; let rIdx = $index) {
        <tr [style.background-color]="hoveredRow() === rIdx ? '#fff3cd' : ''">
          <td style="font-weight:bold">{{ rowP.name }}</td>
          @for (colP of planets; track colP.name; let cIdx = $index) { @let
          rowVal = planetMatrix()[rowP.name]; @let colVal =
          planetMatrix()[colP.name];
          <td
            [style.background-color]="getCellBg(rIdx, cIdx)"
            (mouseenter)="setHover(rIdx, cIdx)"
            (mouseleave)="setHover(null, null)"
          >
            @if (rowP.name === colP.name) { X } @else { @let diff = colVal -
            rowVal;
            {{ (diff < 0 ? diff + 108 : diff) + 1 }}
            }
          </td>
          }
        </tr>
        }
      </tbody>
    </table>
  </div>
</details>
}

<dialog #doshaDialog class="karmicDoshaDialog">
  @if (selectedDosha()) {
  <table>
    <tbody>
      <tr>
        <td>Rasi, Nakshatra</td>
        <td>{{ selectedDosha().rasi }}, {{ selectedDosha().nakshatra }}</td>
      </tr>
      <tr>
        <td>Indications</td>
        <td>{{ selectedDosha().indications }}</td>
      </tr>
      <tr>
        <td>Remedies</td>
        <td>{{ selectedDosha().remidies }}</td>
      </tr>
    </tbody>
  </table>
  }
  <div class="text-center">
    <button (click)="doshaDialog.close()">Close</button>
  </div>
</dialog>

<dialog #resultsDialog>
  <div [innerHTML]="karmicResultsHtml()"></div>
  <div class="text-center">
    <button (click)="resultsDialog.close()">Close</button>
  </div>
</dialog>

// src/components/astroParseTable/AstroParseTable.tsx
import { useRef, useState } from 'preact/hooks';
import { NAVAMSA_COMBINATION } from '../../data/constants';
import { KarmicDoshas } from '../../data/KarmicDoshas';
import { NakshatraPadaData } from '../../data/NakshatraPada.data';
import { parseAstroText } from '../../helpers';
import type { NakshatraData, NakshatraPadas } from '../../models';
import type { AstroRowData } from './AstroParseTable.model';
import styles from './AstroParseTable.module.scss';

const planets = [
  { name: 'As' },
  { name: 'Sun' },
  { name: 'Moon' },
  { name: 'Mars' },
  { name: 'Mercury' },
  { name: 'Jupiter' },
  { name: 'Venus' },
  { name: 'Saturn' },
  { name: 'Rahu' },
  { name: 'Ketu' },
  { name: 'Uranus' },
  { name: 'Neptune' },
  { name: 'Pluto' },
  { name: 'Maandi' },
  { name: 'Bhrigu Bindu' }
];

export function AstroParseTable() {
  const [input, setInput] = useState('');
  const [rows, setRows] = useState<AstroRowData[]>([]);
  const [hoveredRowIndex, setHoveredRowIndex] = useState<number | null>(null);
  const [hoveredColIndex, setHoveredColIndex] = useState<number | null>(null);
  const [selectedPlanetDetails, setSelectedPlanetDetails] = useState<
    ((typeof KarmicDoshas)[string] & { rasi: string }) | null
  >(null);

  const planetMatrixRef = useRef<Record<string, number>>({});
  const dialogRef = useRef<HTMLDialogElement>(null);

  const handleSubmit = () => {
    const parsedRows = parseAstroText(input);
    planetMatrixRef.current = {};
    parsedRows.forEach((item) => {
      let planetName = item.body.trim().split(' ')[0];
      if (planetName === 'Lagna') {
        planetName = 'As';
      }

      if (planetName === 'Bhrigu') {
        planetName = 'Bhrigu Bindu';
      }

      // Handle potential leading space or (R)
      if (planetName.includes('(R)')) {
        planetName = planetName.replace(' (R)', '');
      }
      // Normalize Cancer: Cn -> Ca
      let d1Code = item.rasiCode;
      if (d1Code === 'Cn') {
        d1Code = 'Ca';
      }
      let d9Code = item.navamsaCode;
      if (d9Code === 'Cn') {
        d9Code = 'Ca';
      }
      // Get navamsa number
      const navamsaNum = NAVAMSA_COMBINATION[`${d1Code},${d9Code}` as keyof typeof NAVAMSA_COMBINATION];
      if (navamsaNum) {
        planetMatrixRef.current[planetName] = navamsaNum;
      }
    });
    setRows(parsedRows);
  };

  const handleCellHover = (rowIndex: number, colIndex: number) => {
    setHoveredRowIndex(rowIndex);
    setHoveredColIndex(colIndex);
  };

  const handleMouseLeave = () => {
    setHoveredRowIndex(null);
    setHoveredColIndex(null);
  };

  const getCellStyle = (rowIndex: number, colIndex: number) => {
    const isHoveredRow = hoveredRowIndex === rowIndex;
    const isHoveredCol = hoveredColIndex === colIndex;
    const isIntersection = isHoveredRow && isHoveredCol;

    if (isHoveredRow || isHoveredCol) {
      return {
        backgroundColor: isIntersection ? '#ffeb3b' : '#fff3cd' // Yellowish for highlight, darker for intersection
      };
    }
    return {};
  };

  const getRowStyle = (rowIndex: number) => {
    return hoveredRowIndex === rowIndex ? { backgroundColor: '#fff3cd' } : {};
  };

  const getColStyle = (colIndex: number) => {
    return hoveredColIndex === colIndex ? { backgroundColor: '#fff3cd' } : {};
  };

  const handleViewKarmicDosha = (nakshatraCode: string, rasi: string) => {
    setSelectedPlanetDetails({ ...KarmicDoshas[nakshatraCode], rasi });
    dialogRef.current?.showModal();
  };

  return (
    <div>
      <textarea
        rows={15}
        cols={120}
        placeholder="Paste astrology data here..."
        value={input}
        onInput={(e) => setInput((e.target as HTMLInputElement).value)}
        className={styles.formControl}
      />

      <div className={`text-center ${styles.actions}`}>
        <button onClick={handleSubmit}>Generate Table</button>
      </div>

      {rows.length > 0 ? (
        <>
          <details>
            <summary>
              <strong>Planet Details</strong>
            </summary>
            <div>
              <table className={styles.planetDetails}>
                <thead>
                  <tr>
                    <th>Body</th>
                    <th>Longitude</th>
                    <th>Nakshatra</th>
                    <th>Pada</th>
                    <th>Rasi (D1)</th>
                    <th>Navamsa (D9)</th>
                    <th>Charecterstics</th>
                    <th>Career Path</th>
                    <th>Has Karmic Dosha</th>
                    <th>Karmic Planet</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((row, idx) => (
                    <tr key={idx}>
                      <td>{row.body}</td>
                      <td>{row.longitude}</td>
                      <td data-nakshatra={`${row.nakshatraCode},${row.pada}`}>{row.nakshatra}</td>
                      <td>{row.pada}</td>
                      <td>{row.rasi}</td>
                      <td>{row.navamsa}</td>
                      <td>
                        {
                          NakshatraPadaData[row.nakshatraCode as keyof NakshatraData][row.pada as keyof NakshatraPadas][
                            'Characteristics'
                          ]
                        }
                      </td>
                      <td>
                        {
                          NakshatraPadaData[row.nakshatraCode as keyof NakshatraData][row.pada as keyof NakshatraPadas][
                            'Career Path'
                          ]
                        }
                      </td>
                      <td>
                        {row.hasKarmicDosha ? (
                          <>
                            <span>Yes</span>
                            <button data-size="sm" onClick={() => handleViewKarmicDosha(row.nakshatraCode, row.rasi)}>
                              View
                            </button>
                          </>
                        ) : (
                          'No'
                        )}
                      </td>
                      <td>{row.karmicPlanet}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </details>

          <details>
            <summary>
              <strong>Navamsa Matrix</strong>
            </summary>
            <div>
              <table className={styles.matrixTable}>
                <thead>
                  <tr>
                    <th></th>
                    {planets.map((planet, index) => (
                      <th key={index} style={{ ...getColStyle(index) }}>
                        {planet.name}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {planets.map((rowPlanet, rowIndex) => (
                    <tr key={rowIndex} style={getRowStyle(rowIndex)}>
                      <td style={{ ...getColStyle(-1) }}>{rowPlanet.name}</td>
                      {planets.map((colPlanet, colIndex) => {
                        const rowPlanetNumber = planetMatrixRef.current[rowPlanet.name];
                        const columnPlanetNumber = planetMatrixRef.current[colPlanet.name];
                        const difference = columnPlanetNumber - rowPlanetNumber;
                        const isSamplePlanet = rowPlanet.name === colPlanet.name;

                        return (
                          <td
                            style={{
                              cursor: 'pointer',
                              ...getCellStyle(rowIndex, colIndex)
                            }}
                            onMouseEnter={() => handleCellHover(rowIndex, colIndex)}
                            onMouseLeave={handleMouseLeave}
                          >
                            {isSamplePlanet ? 'X' : (difference < 0 ? difference + 108 : difference) + 1}
                          </td>
                        );
                      })}
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </details>
        </>
      ) : null}

      <dialog ref={dialogRef} className={styles.karmicDoshaDialog}>
        <table>
          <tbody>
            <tr>
              <td>Rasi, Nakshatra</td>
              <td>
                {selectedPlanetDetails?.rasi}, {selectedPlanetDetails?.nakshatra}
              </td>
            </tr>
            <tr>
              <td>Indications</td>
              <td>{selectedPlanetDetails?.indications}</td>
            </tr>
            <tr>
              <td>Remidies</td>
              <td>{selectedPlanetDetails?.remidies}</td>
            </tr>
          </tbody>
        </table>
        <div>
          <button onClick={() => dialogRef.current?.close()}>Close</button>
        </div>
      </dialog>
    </div>
  );
}
